Fix Minor Issue + more
Majored/mcm-js-api-wrapper pull request #1
Opened 2022-01-08 02:22 UTC by steamworksmc

Patched a minor issue with the conversations endpoint (wrapper-side). Route requests parameter named 'recipient_ids' when 'recipient-id' was provided. The entire project was linted, and replaced old 'example' token with the URL on how to obtain an API Key.

2022-01-08 21:19 UTC, Majored requested changes
Thank you for your swift initiative with this PR rather than solely submitting issues. 
Helps a ton given I'm currently within an exam period. 👍 

Just two small things regarding linter max line width & Private vs Shared tokens within two of the examples.

2022-01-08 21:19 UTC, Majored commented on examples/action_on_ban.js
> +const token = {
Could you run the linter again but with a max line width of 120 rather than 80?

2022-01-08 21:19 UTC, Majored commented on examples/license_check.js
> +  type: "Private",
This type would need to be kept Shared as it's demonstrating using injected placeholders to validate a license, and you obviously shouldn't/wouldn't be sharing Private tokens.

Feel free to also write a comment if you wish to reflect this so it's doesn't potentially confuse anyone else.

2022-01-08 21:19 UTC, Majored commented on examples/version_check.js
> +  type: "Private",
Same as the previous comment regarding Shared tokens.

2022-01-08 21:45 UTC, imsteamworks commented on examples/version_check.js
> +  type: "Private",
Small adjustments were made inside of the files where private token types could be used (same as the change above).

2022-01-08 21:45 UTC, steamworksmc commented on examples/action_on_ban.js
> +const token = {
Fixed, lint-width is now set to 120 rather than 80.

2022-01-09 09:48 UTC, Majored approved these changes

2022-01-09 09:50 UTC, Majored commented
Thanks for that, merging. 👍

2022-01-09 09:52 UTC, merged